---

- hosts: localhost
  connection: local
  become: false

  vars:
    work_dir: "{{ playbook_dir }}/setup"
    demo_repo_url: "git@github.com:anthcourtney/ansible-meetup-demo.git"
    demo_repo_name: "ansible-meetup-demo"

  tasks:

  - name: Make temp vagrant directory
    file:
      path: "{{ work_dir }}"
      state: directory

  - name: Clone ansible-meetup-demo repo
    git:
      repo: "{{ demo_repo_url }}"
      dest: "{{ work_dir }}/{{ demo_repo_name }}"
      version: master
      update: yes

  - name: Install ansible-meetup-demo requirements
    command: make requirements
    args:
      chdir: "{{ work_dir }}/{{ demo_repo_name }}"
    
