---

- hosts: all
  become: true

  tasks:

  - name: Install epel
    package:
      name: epel-release
      state: present

  - name: Install pip + ansible pre-reqs
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python-pip
      - gcc
      - openssl-devel
      - python-devel

  - name: Install ansible
    pip:
      name: ansible
      version: 2.2.1.0
